services:

  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    #      MONGO_INITDB_DATABASE: init
    ports:
      - "27017:27017"
    volumes:
      - ./db_data/:/data/db/
      - /etc/timezone:/etc/timezone:ro
    networks:
      - my_network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - my_network

networks:
  my_network:
    driver: bridge # Let Docker create the network
